name: GLFW for MS-DOS
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-msdos
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/volkertb/debian-djgpp
    steps:
      - uses: actions/checkout@v4

      - name: Compile
        id: compile
        env:
          FLAGS: ""
        run: |
          cd msdos && make

